spring:
  thymeleaf:
    cache: false
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

github:
  clientId: 45433d33477f5f586e86
  clientSecret: e99d5e5e455c4eb87269c00a654527e397dc7c2b
  redirectUri: http://localhost:8080/callback


mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.personal.mapper.*: debug

